// ACCOUNT ACTIONS
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FORGOTTEN_PASSWORD_REQUEST = 'FORGOTTEN_PASSWORD_REQUEST';
export const FORGOTTEN_PASSWORD_SUCCESS = 'FORGOTTEN_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

// LOCATION ACTIONS
export const GET_USER_LOCATION_REQUEST = 'GET_USER_LOCATION_REQUEST';
export const GET_USER_FOREGROUND_LOCATION_SUCCESS = 'GET_USER_FOREGROUND_LOCATION_SUCCESS';
export const GET_USER_FOREGROUND_LOCATION_FAILURE = 'GET_USER_FOREGROUND_LOCATION_FAILURE';

// WISHLIST ACTIONS
export const TOGGLE_WISHLIST_ITEM_REQUEST = 'TOGGLE_WISHLIST_ITEM_REQUEST';
export const TOGGLE_WISHLIST_ITEM_SUCCESS = 'TOGGLE_WISHLIST_ITEM_SUCCESS';

// ENTRANCES ACTIONS
export const ADD_ENTRANCE_REQUEST = 'ADD_ENTRANCE_REQUEST';
export const ADD_ENTRANCE_SUCCESS = 'ADD_ENTRANCE_SUCCESS';
export const EDIT_ENTRANCE_REQUEST = 'EDIT_ENTRANCE_REQUEST';
export const EDIT_ENTRANCE_SUCCESS = 'EDIT_ENTRANCE_SUCCESS';
export const REMOVE_ENTRANCE_REQUEST = 'REMOVE_ENTRANCE_REQUEST';
export const REMOVE_ENTRANCE_SUCCESS = 'REMOVE_ENTRANCE_SUCCESS';

// PEAKS ACTIONS
export const GET_PEAKS_IDS_REQUEST = 'GET_PEAKS_IDS_REQUEST';
export const GET_PEAKS_IDS_SUCCESS = 'GET_PEAKS_IDS_SUCCESS';
export const GET_PEAKS_BY_IDS_REQUEST = 'GET_PEAKS_BY_IDS_REQUEST';
export const GET_PEAKS_BY_IDS_SUCCESS = 'GET_PEAKS_BY_IDS_SUCCESS';

// MAP ACTIONS
export const SET_ACTIVE_MAP_FILTERS = 'SET_ACTIVE_MAP_FILTERS';

// SEARCH ACTIONS
export const SET_ACTIVE_SEARCH_FILTERS = 'SET_ACTIVE_SEARCH_FILTERS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

// ACTIVITIES ACTIONS
export const START_ACTIVITY = 'START_ACTIVITY';
export const STOP_ACTIVITY = 'STOP_ACTIVITY';
export const CANCEL_ACTIVITY = 'CANCEL_ACTIVITY';
export const ADD_LOCATION_POINT = 'ADD_LOCATION_POINT';
export const ADD_VISITED_PEAK = 'ADD_VISITED_PEAK';
export const REMOVE_VISITED_PEAK = 'REMOVE_VISITED_PEAK';
export const SAVE_ACTIVITY_REQUEST = 'SAVE_ACTIVITY_REQUEST';
export const SAVE_ACTIVITY_SUCCESS = 'SYNC_ACTIVITY_SUCCESS';